---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - policies.kreepy.jays-lab.de
  resources:
  - crdcleanuppolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policies.kreepy.jays-lab.de
  resources:
  - crdcleanuppolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policies.kreepy.jays-lab.de
  resources:
  - crdcleanuppolicies/status
  verbs:
  - get
  - patch
  - update
