apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multisamples.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: multisamples
    singular: multisample
    kind: MultiSample
    shortNames:
      - smpm
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            spec:
              type: object
              properties:
                fieldA:
                  type: string
    - name: v2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            spec:
              type: object
              properties:
                fieldA:
                  type: string
                fieldB:
                  type: string
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            spec:
              type: object
              properties:
                fieldA:
                  type: string
                fieldB:
                  type: string
                fieldC:
                  type: string
