apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: samples
    singular: sample
    kind: Sample
    shortNames:
      - smp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            spec:
              type: object
              properties:
                fieldA:
                  type: string
