name: Publish OLM Release

on:
  release:
    types: [published] # Trigger the workflow only when a new release is created
env:
  REGISTRY: ghcr.io

jobs:
  release-olm:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set release version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make bundle
        run: |
          make bundle IMG="${{ env.REGISTRY }}/${{ github.repository }}-operator:${RELEASE_VERSION}"

      - name: Build and push operator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-operator:${{ env.RELEASE_VERSION }}

      - name: Build and push operator bundle image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-bundle:${{ env.RELEASE_VERSION }}

      - name: Generate operator catalog
        uses: docker://quay.io/operator-framework/opm
        with:
          entrypoint: /bin/sh
          args: -c "mkdir -p catalog/operator && \
            opm alpha render-template semver semver.yaml > catalog/operator/catalog.yaml && \
            opm validate catalog/operator && \
            opm generate dockerfile catalog/operator"

      - name: Build and push operator catalog image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: catalog/operator.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}-catalog:stable
